//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicknameGenerator {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NicknameGenerator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на aback
        ///abaft
        ///abandoned
        ///abashed
        ///aberrant
        ///abhorrent
        ///abiding
        ///abject
        ///ablaze
        ///abnormal
        ///aboard
        ///aboriginal
        ///abortive
        ///abounding
        ///abrasive
        ///abrupt
        ///absent
        ///absorbed
        ///absorbing
        ///abstracted
        ///absurd
        ///abusive
        ///acceptable
        ///accessible
        ///accidental
        ///accurate
        ///acoustic
        ///acrid
        ///ad hoc
        ///adamant
        ///adaptable
        ///addicted
        ///adhesive
        ///adjoining
        ///adorable
        ///afraid
        ///agonizing
        ///ahead
        ///alcoholic
        ///alert
        ///alike
        ///alive
        ///alleged
        ///alluring
        ///aloof
        ///ambiguous
        ///ambitious
        ///amuck
        ///ancient
        ///animated
        ///apathetic
        ///aquatic
        ///aromatic
        ///aspiring
        ///a [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Adjectives {
            get {
                return ResourceManager.GetString("Adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на account
        ///act
        ///adjustment
        ///advertisement
        ///agreement
        ///air
        ///amount
        ///amusement
        ///animal
        ///answer
        ///apparatus
        ///approval
        ///argument
        ///art
        ///attack
        ///attempt
        ///attention
        ///attraction
        ///authority
        ///back
        ///balance
        ///base
        ///behavior
        ///belief
        ///birth
        ///bit
        ///bite
        ///blood
        ///blow
        ///body
        ///brass
        ///bread
        ///breath
        ///brother
        ///building
        ///burn
        ///burst
        ///business
        ///butter
        ///canvas
        ///care
        ///cause
        ///chalk
        ///chance
        ///change
        ///cloth
        ///coal
        ///color
        ///comfort
        ///committee
        ///company
        ///comparison
        ///competition
        ///condition
        ///connection
        ///control
        ///cook
        ///copper
        ///copy
        ///cork
        ///copy
        ///cou [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Nouns {
            get {
                return ResourceManager.GetString("Nouns", resourceCulture);
            }
        }
    }
}
